# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    #directory: "terraform/terraform-modules/aci/aaep/" # customer-managed-keys module 
    directory: "terraform/terraform-modules/aci/epg-to-domain"
    commit-message:
      prefix: "feat(deps):"
    schedule:
      interval: "montly"
      day: "sunday"
    labels:
      - "terraform"
      - "dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "montly"
      day: "sunday"
    commit-message:
      prefix: "feat(deps):"
    labels:
      - "github-actions"
      - "dependabot"
      - "dependabot"
