# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
default_stages:
  - commit
  - push
fail_fast: False
repos:
# General hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: |
        (?x)^(
            .*ci\/pipeline.yaml |
        )$
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-symlinks
  - id: debug-statements
  - id: detect-aws-credentials
    args:
      - --allow-missing-credentials
  - id: detect-private-key
  - id: no-commit-to-branch
    name: no-commit-to-dev
    args:
      - --branch
      - dev
  - id: mixed-line-ending
    args: [ --fix=lf ]
  - id: requirements-txt-fixer
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]
    args: [ "--profile", "black" ]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.2
  hooks:
    - id: terraform_fmt
      #- id: terraform_checkov
      #args:
      #  - --args=--config-file __GIT_WORKING_DIR__/checkov.yaml
