name: Pre-commit

on:
 push:
  branches:
      - main
 workflow_dispatch:
 pull_request:
 release:
   types: [created]

jobs:
  pre-commit:

    runs-on: ubuntu-latest
    container:
      image: 75devendra/pre-commit:0.0

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Enable GIT
        run: apt update; apt install git -y; git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: 1.2.3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up Gitlint
        run: pip install gitlint

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Init TFLint
        run: tflint --init

      - uses: pre-commit/action@v3.0.0
        with:
            extra_args: --files all
