on:
  push:
    branches:
      - main
      - pull_request

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write 

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Render terraform docs inside the README.md and push changes back to main
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
